name: Build and Deploy to NCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: 코드 빌드
        run: |
          # 코드 빌드 스크립트 또는 명령어를 실행합니다.
          # 예를 들어, npm install 및 npm build를 실행하거나 Docker 이미지 빌드를 할 수 있습니다.

      - name: 코드 NCP Git 저장소로 push
        run: |
          # NCP Git 저장소의 SSH URL을 사용하여 remote를 추가합니다.
          git remote add ncp ssh://devtools.ncloud.com/3051952/NewMVCShop.git
          
          # GitHub Actions Secret에 저장한 SSH 공개 키를 설정합니다.
          echo "$NCP_SSH_HOST_KEY" > ncp_ssh_key
          
          # 코드를 NCP Git 저장소로 push합니다.
          GIT_SSH_COMMAND="ssh -i ncp_ssh_key" git push ncp main:main
