name: Build, Deploy, and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install Dependencies
        run: npm install
        working-directory: src/main/reactfront

      - name: Build React App
        run: npm run build
        working-directory: src/main/reactfront

      - name: Build Spring Boot Application
        run: ./gradlew build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./build/libs/ROOT.war src/main/reactfront/build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
=======
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 필요한 Java 버전으로 변경하세요

      - name: Build WAR
        run: |
          ./gradlew clean build  # Gradle 빌드 명령을 사용하여 WAR 파일을 생성합니다
        #working-directory: ./path/to/your/project  # 프로젝트 디렉토리 경로로 수정하세요
>>>>>>> parent of 892d8f6 (test)

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/tag-name:latest
          cache-from: type=registry,ref=${{ secrets.NCP_CONTAINER_REGISTRY }}/prv-frontend:latest
          cache-to: type=inline
