name: auto deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push to NCP container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build WAR
        run: |
          ./gradlew clean build  # Gradle 빌드 명령을 사용하여 WAR 파일을 생성합니다
        #working-directory: ./path/to/your/project  # 프로젝트 디렉토리 경로로 수정하세요

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/tag-name:latest
          cache-from: type=registry,ref=${{ secrets.NCP_CONTAINER_REGISTRY }}/prv-frontend:latest
          cache-to: type=inline
